### ISSUE TITLE
执行完命令后台还是打不开

### ISSUE THREAD

**Issue by wsdo** [surmon-china/angular-admin#11]
执行npm i 
npm start

让输入密码什么的，怎么直接进入页面

**Comment by surmon-china** [comment]
https://github.com/surmon-china/angular-admin#angular-admin

**Comment by surmon-china** [comment]
If you only need to demonstrate the project locally, you need to comment on the following lines of code:

src/app/app.component.ts:54
src/app/app.component.ts:114
src/app/app.component.ts:120

**Comment by EnochGao** [comment]
是把54，114,120行注释吗？注释后还是不行呀

**Comment by surmon-china** [comment]
更新了，重新看一下
