### ISSUE TITLE
如何更改背景色呢

### ISSUE THREAD

**Issue by zhangwonderful** [surmon-china/angular-admin#12]
您好，请问如果要把灰色背景换成其他背景色在哪里修改呢

**Comment by surmon-china** [comment]
https://github.com/surmon-china/angular-admin/blob/master/src/app/theme/theme.config.ts
https://github.com/surmon-china/angular-admin/tree/master/src/app/theme/sass/conf/colorSchemes

**Comment by zhangwonderful** [comment]
谢谢
