### ISSUE TITLE
项目克隆下来，执行npm i 后 启动的时候出现错误

### ISSUE THREAD

**Issue by wsdo** [surmon-china/angular-admin#14]
![image](https://user-images.githubusercontent.com/9738969/29250514-2e7e06fe-8076-11e7-91cb-fcaf4f3ec99a.png)

**Comment by HalleyLi** [comment]
解决了吗，我也出现这个问题

**Comment by ghost** [comment]
我也是，不知道怎么结局了

**Comment by Kimmyzhao** [comment]
有解决的么

**Comment by surmon-china** [comment]
年久失修，看起来是 bootstrap 测试版引起的问题

**Comment by surmon-china** [comment]
更新到最新，已全部解决
