### ISSUE TITLE
能支持动态多tab导航吗？

### ISSUE THREAD

**Issue by runtop** [surmon-china/angular-admin#2]
看了github一大堆angular admin的template，没有一个是点击左侧菜单在主容器动态打开一个tab， 这样可以同时打开多个菜单，多个tab可以切换。

**Comment by surmon-china** [comment]
好奇怪的需求，你可以自己实现

**Comment by runtop** [comment]
大部分的后台admin管理系统，不都是这个样子的吗？ 左边菜单树（会有多级），右边主容器是一个tabs容器，点击左边的菜单后，可以在tabs里面增加一个tab并显示对应的操作界面，比如： 菜单有人员管理/订单管理/商品管理/分类管理/采购管理/费用管理等等， 点击打开以上所有菜单，右边主容器的同时会存在所有打开的tab页，每个tab页里面有对应的操作界面；点击tab页头部可以切换界面。
就像我同时要看订单列表，也要看费用列表等等。

**Comment by surmon-china** [comment]
我明白你的需求了，你的描述是从UI的角度来的，但实际上内容区的"Tab"和左侧的菜单是没有关系的，菜单做的事仅仅是导航到某个页面，Tab应属于页面内的布局和内容了，你可以参考[ng2-bootstrap](http://valor-software.com/ng2-bootstrap/#/tabs)实现你的需求，本项目由于需要实际生产，不便增加，建议fork后自行添加，感谢反馈。
