### ISSUE TITLE
api.service.ts是不是没有上传呢

### ISSUE THREAD

**Issue by ghost** [surmon-china/angular-admin#20]
帅哥能否上传下，作为第100名forker想通过你项目学下angular

**Comment by surmon-china** [comment]
这个吗？

https://github.com/surmon-china/angular-admin/blob/master/src/app/services/saHttpRequester/saHttpRequester.service.ts

**Comment by ghost** [comment]
哦，这回看懂了，谢谢大神，大神劳动节快乐
