### ISSUE TITLE
打包是否支持下AOT

### ISSUE THREAD

**Issue by zhytang** [surmon-china/angular-admin#28]

**Comment by surmon-china** [comment]
似乎是被某个插件所限，如果你可以解决，欢迎 PR。

（我来解决的话可能需要等很长一段时间。

**Comment by zhytang** [comment]
好的，能否告知是哪个插件。

**Comment by zhytang** [comment]
> 似乎是被某个插件所限，如果你可以解决，欢迎 PR。
> 
> （我来解决的话可能需要等很长一段时间。

好的，是否还记得是哪个插件。

**Comment by surmon-china** [comment]
mark: v3.3.0 发布时关闭此 Issue。

**Comment by surmon-china** [comment]
[PR#40](https://github.com/surmon-china/angular-admin/pull/40)，现已支持。
