### ISSUE TITLE
 ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by zhangwonderful** [surmon-china/angular-admin#5]
我的环境是centos 7,npm 7.8.0.
当我执行 npm run build:prod 时，报下列错误，不知道是什么原因,麻烦作者您给点思路，非常感谢。
Module '"/opt/angular2/ng2/angular-admin/node_modules/ng2-bootstrap/index"' has no exported member 'DropdownModule'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-admin@1.1.0 webpack: `webpack --progress --profile --bail "--config" "config/webpack.prod.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-admin@1.1.0 webpack script 'webpack --progress --profile --bail "--config" "config/webpack.prod.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --profile --bail "--config" "config/webpack.prod.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-admin
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-04-04T02_08_35_463Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-admin@1.1.0 build:prod: `npm run webpack -- --config config/webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-admin@1.1.0 build:prod script 'npm run webpack -- --config config/webpack.prod.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run webpack -- --config config/webpack.prod.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-admin
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by zhangwonderful** [comment]
运行npm install出现下列warn信息
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/tsc-wrapped@4.0.1 requires a peer of typescript@^2.1.5 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN angular2-jwt@0.1.28 requires a peer of @angular/http@^2.0.0 but none was installed.
npm WARN angular2-notifications@0.4.53 requires a peer of @angular/core@^2.1.2 but none was installed.
npm WARN angular2-notifications@0.4.53 requires a peer of @angular/common@^2.1.2 but none was installed.
npm WARN angular2-notifications@0.4.53 requires a peer of @angular/platform-browser@^2.1.1 but none was installed.
npm WARN ng2-smart-table@0.3.2 requires a peer of @angular/common@2.1.1 but none was installed.
npm WARN ng2-smart-table@0.3.2 requires a peer of @angular/compiler@2.1.1 but none was installed.
npm WARN ng2-smart-table@0.3.2 requires a peer of @angular/core@2.1.1 but none was installed.
npm WARN ng2-smart-table@0.3.2 requires a peer of @angular/forms@2.1.1 but none was installed.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none was installed.

**Comment by zhangwonderful** [comment]
运行npm start，报下列错误：
[default] /opt/angular2/ng2/angular-admin/src/app/pages/announcement/announcement.module.ts:4:28 
    Module '"/opt/angular2/ng2/angular-admin/node_modules/ng2-bootstrap/index"' has no exported member 'DropdownModule'.
[default] /opt/angular2/ng2/angular-admin/src/app/pages/article/article.module.ts:5:28 
    Module '"/opt/angular2/ng2/angular-admin/node_modules/ng2-bootstrap/index"' has no exported member 'DropdownModule'.
[default] /opt/angular2/ng2/angular-admin/src/app/pages/comment/comment.module.ts:5:28 
    Module '"/opt/angular2/ng2/angular-admin/node_modules/ng2-bootstrap/index"' has no exported member 'DropdownModule'.
[default] /opt/angular2/ng2/angular-admin/src/app/pages/demo/ui/ui.module.ts:7:28 
    Module '"/opt/angular2/ng2/angular-admin/node_modules/ng2-bootstrap/index"' has no exported member 'DropdownModule'.
[default] Checking finished with 4 errors

**Comment by surmon-china** [comment]
尝试下把引用`ng2-bootstrap`的地方改为引用`ng2-bootstrap/ng2-bootstrap`，具体原因无法确定，我暂时没有太多时间去测试，可能是`ng2-bootstrap`版本引起的问题

**Comment by s-sevenup** [comment]
has no exported member 'DropdownModule是因为ng2-bootstrap的DropdownModule模块名不对，
BsDropdownModule才对

**Comment by surmon-china** [comment]
@xihadandan 正确，`ng2-bootstrap`已升级并更名到`ngx-bootstrap`，稍后更新修复这个问题。

**Comment by surmon-china** [comment]
@zhangwonderful 问题已解决，重新clone或者pull呦

**Comment by zhangwonderful** [comment]
谢谢,可以了，就是版本的问题，，升级了就好了。
