### ISSUE TITLE
关于七牛云文件的上传

### ISSUE THREAD

**Issue by Hjyheart** [surmon-china/angular-admin#9]
您好，看了您的代码，觉得很屌，很是震撼。但是有个小小的疑问我不是很懂。就是那个七牛云上传为什么要写三个按钮。我尝试去用正常的脑回路上传文件，发现并不行，然后抄了您的代码就可以了，我很是不解，希望您可以解答我心中的疑惑。

**Comment by surmon-china** [comment]
你指这个吗？
https://github.com/surmon-china/angular-admin/blob/master/src/app/theme/components/baPictureUploader/baPictureUploader.html

其实就两个事件：
- 删除当前图片（已上传图片）
- 重新上传图片/或者说是上传图片

**Comment by Hjyheart** [comment]
是 是这段代码 我不懂为什么这边要用到三个按钮 七牛云sdk绑定的那个按钮甚至都没有用 第一个按钮的点击事件只是去模拟点击第二个隐藏的按钮 就不是很懂这个逻辑 但不这么做似乎又传不上文件 就来讨教一下这个“三按钮”大法的原理

**Comment by surmon-china** [comment]
https://github.com/surmon-china/angular-admin/blob/master/src/app/theme/components/baPictureUploader/baPictureUploader.component.ts#L150

https://github.com/surmon-china/angular-admin/blob/master/src/app/theme/components/baPictureUploader/baPictureUploader.component.ts#L20

https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html#!#invokeElementMethod-anchor

看这里就明白啦，用几个按钮不重要，重要的是用按钮发起input控件原生的上传方法，使用的是`invokeElementMethod`这个API。

**Comment by surmon-china** [comment]
另外，七牛云sdk提供的按钮确实没用上，而是直接调用了七牛云sdk的上传文件api。

代码在此：https://github.com/surmon-china/angular-admin/blob/master/src/app/theme/components/baPictureUploader/baPictureUploader.component.ts#L146

**Comment by Hjyheart** [comment]
非常感谢
